export { default as Magnifier } from './Magnifier'
export { default as Github } from './Github'
export { default as Email } from './Email'
export { default as Logo } from './Logo'
export { default as Play } from './Logo'
export { default as Pause } from './Logo'
export { default as Stop } from './Logo'
